# Generated by Django 4.2.5 on 2023-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unique_skill', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
