# Generated by Django 4.2.5 on 2023-09-08 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.UUID('d583eb43-750b-45b6-bc8f-15ca5eba0ebb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
