# Generated by Django 4.2.5 on 2023-09-10 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.UUID('66e4f644-4e5c-4089-b17c-a9ef0d8c4ad2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
