# Generated by Django 4.2.5 on 2023-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='char_name',
            field=models.CharField(default='Kermel', max_length=100),
        ),
    ]
