# Generated by Django 4.2.5 on 2023-09-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inventory_char_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
