# Generated by Django 4.2.5 on 2023-09-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_inventory_power_alter_inventory_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventory',
            new_name='Item',
        ),
    ]
