# Generated by Django 4.2.5 on 2023-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_item_description_alter_item_unique_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unique_skill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
