# Generated by Django 4.2.5 on 2023-09-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_item_description_alter_item_unique_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='char_name',
            field=models.CharField(default='Kernel', max_length=100),
        ),
    ]
