# Generated by Django 4.2.5 on 2023-09-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_item_char_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='char_name',
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
